In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4,5,3])
print(arr.shape)
arr.reshape(2,3)



(6,)


array([[1, 2, 3],
       [4, 5, 3]])

In [20]:
# Creating an array using the arrange function

arr2 = np.arange(start=-5,stop=-10,step=-1)
print(arr2)

[-5 -6 -7 -8 -9]


In [24]:
arr_zero =  np.zeros((5,5))
print(arr_zero)

arr_one = np.ones((5,5))
print(arr_one)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
identity_mat = np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
## NUMPY VECTORIZED OPERATOINS

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])

#element wise operations
print(f"ELement Wise Addition : {arr1+arr2}")
print(f"ELement Wise subtraction : {arr1-arr2}")
print(f"ELement Wise multiplication : {arr1*arr2}")
print(f"ELement Wise division : {arr1/arr2}")


ELement Wise Addition : [ 7  9 11 13  5]
ELement Wise subtraction : [-5 -5 -5 -5  5]
ELement Wise multiplication : [ 6 14 24 36  0]
ELement Wise division : [0.16666667 0.28571429 0.375      0.44444444        inf]


C:\Users\Muhammad.Abubakar\AppData\Local\Temp\ipykernel_20340\3292061179.py:10: RuntimeWarning: divide by zero encountered in divide
  print(f"ELement Wise division : {arr1/arr2}")


In [33]:
## STATISTICAL OPERATIONS

arr = np.array([1,2,3,4,5,6,7,8,9])

mean = arr.mean()
std_dev = arr.std()

# standard normal distrubution: hainmg a mean of 0 and standard deviation of 1

normalized_data = (arr-mean)/std_dev

print("NOrmalized Data : ",normalized_data)
print("Normalized mean ", normalized_data.mean())
print("Normalized mean ", normalized_data.std())

NOrmalized Data :  [-1.54919334 -1.161895   -0.77459667 -0.38729833  0.          0.38729833
  0.77459667  1.161895    1.54919334]
Normalized mean  0.0
Normalized mean  1.0


In [35]:
np.__version__

'2.1.3'